### ISSUE TITLE
Bug: Bug doesn't load SP scenario saves

### ISSUE THREAD

**Issue by 6komodo6** [Eagle-Studios/CE_Mods#2]
Hi Eagle,

I faced a weird issue when playing a previous save after updating the blastcore mod. While the mod was loaded I played a SP scenario, saved, then tried loading the save later with the same modlist but it didn't work. Unloading the mod, restarting again, saving and loading worked normally.

The SP scenario in question:
https://steamcommunity.com/sharedfiles/filedetails/?id=3356778268

ty eagle for updating the mod

**Comment by Eagle-Studios** [comment]
Which mods of mine are you loading?

**Comment by 6komodo6** [comment]
Blast core
