### ISSUE TITLE
RHS Edit Issue 12/11/24

### ISSUE THREAD

**Issue by CRISPRcasanev** [Eagle-Studios/CE_Mods#4]
Hello. All the loadout variants are restricted to editing 2x pylons only as seen in this image. https://snipboard.io/ZfKHPo.jpg
Each renamed variant is broken as such. We rely heavily on freely editable pylons with my group, so we would love to have this back to normal!

The weapon additions appear to be contained in Aviation which allows us to use the 7.62 SLAP and HEI/SLAP GAU with normal functioning pylons in the meantime. We still love this mod for the engine performance, flares, and pilot camera!

**Comment by Eagle-Studios** [comment]
1. Seems like the pylon UI position decided to stack itself. 
2. I shall not be editing the hardpoints, to allow for other pylons to be added; you can do this in your own config (It's a realism thing, that RHS has, and I'm following which stops things like a JDAM being attached to the AH6).
