### ISSUE TITLE
RHS Edit - Serverside Dependecy 

### ISSUE THREAD

**Issue by CRISPRcasanev** [Eagle-Studios/CE_Mods#6]
Hi Eagle!
We're updating our server currently and we're getting the error:
|| Warning Message: Addon 'CE_RHSUSAF_AH6M' requires addon 'CE_Flares' ||

Is there anything left in the code that might throw this server-side error? Our Zeus has everything updated to current versions.

Thanks again,
CRISPR

**Comment by Eagle-Studios** [comment]
Are you loading CE - Aviation? bc if not thats your issue

**Comment by Eagle-Studios** [comment]
https://github.com/Eagle-Studios/CE_Mods/wiki/CE-RHSUSAF-Edited
> CE_RHSUSAF_AH6M
```
"rhsusf_main",
"rhsusf_c_airweapons",
"rhsusf_c_heavyweapons",
"rhsusf_c_melb",
"CE_Air_Munitions",
"CE_Flares",
"CE_MAIN"
```

**Comment by CRISPRcasanev** [comment]
Hold on I see he has both @CE - RHS USAF Upgrades and Improvements and @CE - RHSUSAF Edited. My apologies.

**Comment by CRISPRcasanev** [comment]
Probably the old name throwing the error.

**Comment by Eagle-Studios** [comment]
> Hold on I see he has both @ce - RHS USAF Upgrades and Improvements and @ce - RHSUSAF Edited. My apologies.

@ce - RHS USAF Upgrades
is the old version; steam doesnt delete previous files.
BUT there is no way that, that should've been loaded unless manually put there.
